# Travis CI configuration file.

language: php

php:
    - 5.5
    - 5.6
    - 7.0

services:
    - mysql
    
before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS gundi;'
  
install:
    - composer self-update
    - composer install
    
before_script:
    - php bin/gundi db:migrate
    - php bin/gundi seed:run

script:
    - php vendor/bin/codecept run unit
    
